# Algorithm experiments notebook (dirty AF)

## Todo:
* Define a class that holds the state of the table **DONE**
* player 1 and 2 auto switch
* winning rule **DONE**
* droping physics **DONE**

In [11]:
import numpy as np

class Table():
        
    def __init__(self):
        self.table = np.zeros((6,7), dtype=int)
    
    def winning_check(self)-> bool:
        
        def _winning_rule(arr):
            unique = np.unique(arr, return_counts=True)
            winning_player = unique[0][unique[1] > 3]
            return winning_player
        
        def _get_diagonals(a):
            # hacky getting all the diagonals
            diags = [a[::-1,:].diagonal(i) for i in range(-a.shape[0]+1,a.shape[1])]
            diags.extend(a.diagonal(i) for i in range(a.shape[1]-1,-a.shape[0],-1))
            return diags

        def _get_axes(_table):
            axes = []
            for i in range(_table.shape[0]):
                axes.append(_table[i,:])
            for j in range(_table.shape[1]):
                axes.append(_table[:,j])
            return axes
        
        all_axes = []
        all_axes.extend(_get_axes(self.table))
        all_axes.extend(_get_diagonals(self.table))
        
        for ax in all_axes:
            winner = _winning_rule(ax)
            if not  winner:
                # no winner yet
                pass
            else:
                # winner!
                return True
        
    def drop(self, player, j):
        colummn_vec = self.table[:,j]
        non_zero = np.where(colummn_vec != 0)[0]
        
        if non_zero.size == 0:                        
            # sets the stone to the last element 
            self.table[self.table.shape[0]-1,j] = player
        else:                                          
            # sets the stone on the last 0
            self.table[non_zero[0]-1,j] = player
        # checking if winning for every drop!
        if self.winning_check():
            print(f'Player {player} wins!')
        else:
            return self.table 
    
    def reset(self):
        return self.__init__

In [1]:
import numpy as np

In [2]:
mat = np.arange(42).reshape((6,7))

In [3]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

### Get diagonals that intersect `[i,j]`

In [5]:
mat.diagonal(1)

array([ 1,  9, 17, 25, 33, 41])

In [13]:
i, j = 5, 6
print(mat[i,j])
major = np.diagonal(mat, offset=(j - i))
print(major)

minor = np.diagonal(np.rot90(mat), offset=-mat.shape[1] + (j + i) + 1)
print(minor)

41
[ 1  9 17 25 33 41]
[41]


### Get row and column array that pass throught `[i,j]`

In [14]:
row = mat[i,:]
col = mat[:,j]
print(row)
print(col)

[35 36 37 38 39 40 41]
[ 6 13 20 27 34 41]


In [17]:
%timeit x = np.zeros((6,7))

542 ns ± 52.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
x = np.arange(42).reshape((6,7))
%timeit x.fill(0)

511 ns ± 26.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
